### ISSUE TITLE
Unable to use Apollo Federation with GraphQL service

### ISSUE THREAD

**Issue by hitensam** [apollographql/federation-hotchocolate#73] opened 2024-04-11 12:20 UTC
I did only the steps specified in the [Installation](https://github.com/apollographql/federation-hotchocolate?tab=readme-ov-file#installation) but still getting [Banana Cake Pop](https://chillicream.com/docs/bananacakepop/v2/). Please Help!!

## Screenshots:
![image](https://github.com/apollographql/federation-hotchocolate/assets/30778907/0ab8db7a-9b21-4039-880f-c8565919fa0d)
![image](https://github.com/apollographql/federation-hotchocolate/assets/30778907/b1bbe15c-50ab-4ae4-bb2e-0ede2d264a54)

## Project File:
```bash
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.6.0" />
	  <PackageReference Include="ApolloGraphQL.HotChocolate.Federation" Version="1.3.0" />
  </ItemGroup>

</Project>
```

**Comment by mabuyo** [comment] 2024-04-11 15:34
Hi there @hitensam! I'm not sure I understand the issue, are you expecting to see the Apollo Explorer IDE? Or something else?

**Comment by hitensam** [comment] 2024-04-11 15:38
Hi @mabuyo !!!

Thanks for your response 😃.

I was expecting to see something like this: 

![image-4.png](https://github.com/apollographql/federation-hotchocolate/assets/30778907/d60c5f18-8a7c-40a5-860c-ed1cea599aed)

**Comment by mabuyo** [comment] 2024-04-11 15:42
Thanks for clarifying! So it is actually working as intended, since Hot Chocolate ships with their own IDE (Banana Cake Pop). However if you'd like to use the Apollo Explorer IDE, you can go to Studio Sandbox here: https://studio.apollographql.com/sandbox/explorer 

Then update the endpoint to your local endpoint (wherever your GraphQL server is running). You'll also need to update the CORS settings in the Hot Chocolate server:

```cs
builder
  .Services
  .AddCors(options =>
  {
      options.AddDefaultPolicy(builder =>
      {
          builder
              .WithOrigins("https://studio.apollographql.com")
              .AllowAnyHeader()
              .AllowAnyMethod();
      });
  });
```

[We have a lesson on this](https://www.apollographql.com/tutorials/intro-hotchocolate/05-apollo-explorer) if you want more step by step instructions.

Hope this helps! I think there's also a way to update the default IDE, but I have to go searching for it... let me know if you're running into any issues with this approach.

**Comment by hitensam** [comment] 2024-04-11 15:46
Thanks for your help 💯. 

I will try the above said and will get back to you 😄.

**Comment by hitensam** [comment] 2024-04-11 16:50
Firstly, what's this [apollographql/federation-hotchocolate](https://github.com/apollographql/federation-hotchocolate) as I thought it would provide the IDE for the same.

Secondly, I updated CORS but couldn't use [Studio Sandbox](https://studio.apollographql.com/sandbox/explorer). I made the changes according to the [Lesson](https://www.apollographql.com/tutorials/intro-hotchocolate/05-apollo-explorer).

🖼️ ![image](https://github.com/apollographql/federation-hotchocolate/assets/30778907/427fc841-bfa2-416e-b6a6-d7e7b0d0ab90)

Thirdly, It would be great if we could replace [Banana Cake Pop](https://chillicream.com/docs/bananacakepop/v2/) with Apollo Explorer IDE.

If it's not too much to ask, I'd be really grateful if you could provide me with a demo code, as I'm pretty new to GraphQL and we want to implement the same with .NET.

PS: I've already verified my email ID.

**Comment by mabuyo** [comment] 2024-04-11 17:40
> Firstly, what's this [apollographql/federation-hotchocolate](https://github.com/apollographql/federation-hotchocolate) as I thought it would provide the IDE for the same.

To clarify, this repo is a library that works with Hot Chocolate to provide Federation v2 support. 

> Secondly, I updated CORS but couldn't use [Studio Sandbox](https://studio.apollographql.com/sandbox/explorer). I made the changes according to the [Lesson](https://www.apollographql.com/tutorials/intro-hotchocolate/05-apollo-explorer).

Hmm, there might be something extra with CORS happening that's not allowing Sandbox to connect to your server. It's difficult to say without seeing the code to reproduce.

> Thirdly, It would be great if we could replace [Banana Cake Pop](https://chillicream.com/docs/bananacakepop/v2/) with Apollo Explorer IDE.

I would create a new issue and log this as a feature request!

> If it's not too much to ask, I'd be really grateful if you could provide me with a demo code, as I'm pretty new to GraphQL and we want to implement the same with .NET.

Absolutely! We have two courses that walk through GraphQL & Federation with .NET:
- [Intro to GraphQL](https://www.apollographql.com/tutorials/intro-hotchocolate)
- [Federation](https://www.apollographql.com/tutorials/federation-hotchocolate)

And if you'd just like to explore the demo code, you can check out the `final` branches of each course's project code:
- [Intro to GraphQL](https://github.com/apollographql-education/odyssey-intro-hotchocolate/tree/final)
- [Federation](https://github.com/apollographql-education/odyssey-federation-hotchocolate/tree/final)

**Comment by hitensam** [comment] 2024-04-11 18:37
🎉 Once again, a big thank you! I'll diligently follow each step provided in this guide and strive to implement the aforementioned.

👍 Just to confirm: Currently, the only way to utilize the Apollo Explorer IDE is through the Studio Sandbox, accessible [here](https://studio.apollographql.com/sandbox/explorer). Also, any method to override [Banana Cake Pop](https://chillicream.com/docs/bananacakepop/v2/) is considered a feature request at this time.

❓ If there are any issues, is there a way for me to reach out to you?

**Comment by mabuyo** [comment] 2024-04-11 19:31
> 👍 Just to confirm: Currently, the only way to utilize the Apollo Explorer IDE is through the Studio Sandbox, accessible [here](https://studio.apollographql.com/sandbox/explorer). Also, any method to override [Banana Cake Pop](https://chillicream.com/docs/bananacakepop/v2/) is considered a feature request at this time.

Yes and yes :)

> ❓ If there are any issues, is there a way for me to reach out to you?

If you're taking any of the Odyssey courses I linked, there's a GitHub integration in each lesson, you can leave comments there if you're stuck! Otherwise, starting a thread in the [Discord #general channe](https://discord.com/channels/1022972389463687228/1040405752998793236)l also works!

I'm going to close this issue now to keep the project issues clean but feel free to reach out through any of those channels!

**Closed as completed by mabuyo** 2024-04-11 19:31 UTC
